adding type annotations for adafruit_turtle.py
adafruit/Adafruit_CircuitPython_turtle pull request #35
Opened 2023-04-27 15:57 UTC by rrahkola

NOTE: in order to satisfy type annotations, some functions were refactored to maintain immutability of function parameters.  The approach was to use `xn` and `yn` in place of `x1` and `y1`.

2023-04-27 17:53 UTC, tekktrik commented
@kattni @FoamyGuy this PR adds things to `.gitignore`, do we want to keep them and patch them to other libraries to futureproof or keep them out for now?

2023-04-27 17:56 UTC, tekktrik commented
Also @FoamyGuy - we allow import of `__annotations__` since I believe that is now in the CircuitPython firmware, but I think it's just used to allow forward references without quotes.  Thoughts?  We mostly just use quotes elsewhere.

2023-04-27 19:18 UTC, tekktrik requested changes
Thanks for the submission!  Here's a few things I saw other than what's above!

2023-04-27 19:18 UTC, tekktrik commented on adafruit_turtle.py
> +        self._splash: Any = displayio.Group()
I would think this would be `displayio.Group`, was there something that made you type it as `Any`?

2023-04-27 19:18 UTC, tekktrik commented on adafruit_turtle.py
> +        self._odb_tilegrid: Any = None
I think some of these could be narrower than `Any`, but they're also hidden, so it may be worth just leaving them untyped for now.

2023-04-27 19:18 UTC, tekktrik commented on adafruit_turtle.py
> +        x0, y0 = (p[0], p[1])
I'm curious, was there a specific reason these were broken up into do different steps?  Not an issue, just wondering why the function call and unpacking happen separately.

2023-04-27 19:18 UTC, tekktrik commented on adafruit_turtle.py
> +        self, source: Any = None, dimensions: Tuple[int, int] = (12, 12)
I think `source` could be a `Union` of `displayio.TileGrid` and `str`,  wrapped with `Optional`.

2023-04-28 00:01 UTC, FoamyGuy commented
> @kattni @FoamyGuy this PR adds things to `.gitignore`, do we want to keep them and patch them to other libraries to futureproof or keep them out for now?

It does make sense to me to go ahead and accept the changes in gitngore. I think those may be things generated by mypy if run locally which we wouldn't want checked in I don't think.

2023-09-04 16:03 UTC, FoamyGuy approved these changes
I've caught this PR up and had a look over, it's looking good to me now.

The latest commits make the following changes:
- merge from main and resolve conflicts
- adopt all changes request in review
- run pre-commit
- remove a few additional usages of `Any` in favor of more specific types.

Thanks for working on this @rrahkola and to @tekktrik for the initial review.

2023-09-04 16:03 UTC, merged